enable-builtin-rules:
  - aws-access-key-id
  - aws-secret-access-key
  - github-pat
  - github-oauth
  - github-app-token
  - github-refresh-token
  - github-fine-grained-pat
  - gitlab-pat
  - slack-access-token
  - slack-web-hook
  - stripe-secret-token
  - stripe-publishable-token
  - gcp-service-account
  - private-key
  - npm-access-token
  - sendgrid-api-token
  - twilio-api-key
  - heroku-api-key
  - dockerconfig-secret
  - jwt-token
disable-allow-rules:
  - aws-access-key-id
  - aws-secret-access-key
  - github-pat
  - github-oauth
  - github-app-token
  - github-refresh-token
  - github-fine-grained-pat
  - gitlab-pat
  - slack-access-token
  - slack-web-hook
  - stripe-secret-token
  - stripe-publishable-token
  - gcp-service-account
  - private-key
  - npm-access-token
  - sendgrid-api-token
  - twilio-api-key
  - heroku-api-key
  - dockerconfig-secret
  - jwt-token
